#! /usr/bin/env python
# -*- coding: UTF-8 -*-

import os
import sys
import time

sys.stdout = os.fdopen(sys.stdout.fileno(), 'w', 0)

def mtime(f):
    try: return(os.stat(f[0]).st_mtime)
    except OSError, msg:
        print(msg)
        sys.exit(1)

def main():
    nix = os.system
    old = 0
    try: f = sys.argv[1:]
    except IndexError: sys.exit()
    while True:
        if old != mtime(f):
            old = mtime(f)
            print('\n' + '='*20)
            sys.stdout.write(nix('clear; echo "$(./%s) \c"' % ' '.join(f)))
        time.sleep(1)

if __name__ == "__main__":
    try: main()
    except KeyboardInterrupt, msg:
        print(msg)
        sys.exit()











#from collections import OrderedDict as dict
#d = dict([('fisrt', 1),
#    ('second', 2),
#    ('third', 3)])

#d['second'] = 4
#del d['second']
#d['second'] = 5

#print(d.items())


